import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import "@radix-ui/themes/styles.css";
import {Container, Theme, ThemePanel} from "@radix-ui/themes";
import Provider from "./auth/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<Provider>
      
   <Theme accentColor="violet" grayColor="sand">
              <NavBar/>

          
           <main className="p-5">
<Container>

        {children}

</Container>

        </main>
        
        
        </Theme>
    
</Provider>
     
      </body>
    </html>
  );
}
